defaults:
  - _self_
  - task@_global_: manipulator_bring_ball
  - agent@_global_: drm
  - override hydra/launcher: submitit_local
exp_data_path: /home/ripl-pc/Desktop/PROGRESSOR/progressor_ds/metaworld_expert_demonstrations
# task settings
frame_stack: 3
action_repeat: 2
discount: 0.99
# train settings
num_seed_frames: 4000
#num_seed_frames: 500
update_every_steps: 2
reward_model: 'ours'
online_finetune: true
online_finetune_every_step: 100
# eval
eval_every_frames: 10000
num_eval_episodes: 10
# snapshot
save_snapshot: true
# wandb
use_wandb: true
# replay buffer
replay_buffer_size: 1000000
replay_buffer_num_workers: 4
nstep: 3
batch_size: 256
# misc
seed: 121
device: cuda
save_video: true
save_train_video: false
render_reward_on_video: true
use_tb: true
# experiment
experiment: exp
# agent
reward_alpha: 0.4
lr: 1e-4
feature_dim: 50

hydra:
  run:
    dir: ./exp_local/${hydra.job.override_dirname}
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M}_${agent_cfg.experiment}
    subdir: ${hydra.job.num}
  launcher:
    timeout_min: 4300
    cpus_per_task: 10
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 160
    nodes: 1
    submitit_folder: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${agent_cfg.experiment}/.slurm
